export { default as Dashboard } from "./Dashboard";
// export { default as Products } from "./Products";
export { default as AddProduct } from "./AddProduct";
export { default as Customers } from "./Customers";
export { default as OrderManagement } from "./OrderManagement";
export { default as ProductCategories } from "./ProductCategories";
export { default as ProductSales } from "./ProductSales";
export { default as SingleProduct } from "./SingleProduct";

export { default as AddComboOffer } from "./AddComboOffer";
export { default as AddNewArrival } from "./AddNewArrival";
export { default as Coupon } from "./Coupon";
export { default as Faq } from "./Faq";
export { default as FlashOffer } from "./FlashOffer";
export { default as FlashSale } from "./FlashSale";
export { default as FlashSaleManagement } from "./FlashSaleManagement";
export { default as Reviews } from "./InboxManagement";
export { default as PageSettings } from "./PageSettings";
export { default as Pathao } from "./Pathao";
export { default as Settings } from "./Settings";
export { default as SingleOrder } from "./SingleOrder";
export { default as SupplierManagement } from "./Supplier Management/SupplierManagement";
export { default as WebsiteSettings } from "./WebsiteSettings";
